<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net480</TargetFramework>
		<PlatformTarget>x64</PlatformTarget>

		<!-- Modify RootNamespace, AssemblyName, OutputPath, VersionPrefix -->
		<RootNamespace>GenKnowledge</RootNamespace>
		<AssemblyName>RimTalk_GenKnowledge</AssemblyName>
		<OutputPath>../Build/1.6/Assemblies/</OutputPath>
		<VersionPrefix>0.1.0.0</VersionPrefix>
		<BaseIntermediateOutputPath>../Build/obj/</BaseIntermediateOutputPath>

		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<Optimize>true</Optimize>
		<DebugSymbols>true</DebugSymbols>
		<DebugType>portable</DebugType>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
	</PropertyGroup>

 	<ItemGroup>
	 	<Compile Include="../Source/**/*.cs" />
		<Reference Include="$(UserProfile)\.nuget\packages\krafs.rimworld.ref\1.6.4633\ref\net472\*.dll">
			<Private>false</Private>
		</Reference>
		<PackageReference Include="Lib.Harmony" Version="2.3.3" ExcludeAssets="runtime" />
	</ItemGroup>
</Project>
